- name: openSUSE-tumbleweed-playbook
  hosts: localhost
  connection: local

  roles:
    - role: zypper
    - role: ssh
    - role: zsh

  vars_prompt:
    - name: github_token
      prompt: GitHub PAT
