- name: wsl tumbleweed setup
  hosts: localhost
  connection: local

  roles:
    - role: zypper
      tags: zypper
    - role: ssh
    - role: zsh

  vars_prompt:
    - name: github_token
      prompt: GitHub PAT