- name: Set ZSH as the default shell
  become: yes
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /usr/bin/zsh

- name: Check if chezmoi is installed
  stat: path=/home/ant/bin/chezmoi
  register: chezmoi_check

- name: download chezmoi and dotfiles
  shell: sh -c "$(curl -fsLS https://chezmoi.io/get)" -- -b $HOME/.local/bin init --ssh --apply AnthonyEnr1quez
  when: not chezmoi_check.stat.exists
